### ISSUE TITLE
Change DataSource's JNDI name

### ISSUE THREAD

**Issue by btishiwatasns** [terasolunaorg/terasoluna-gfw-functionaltest#106]
jdbc/dataSource -> jdbc/gfwFunctionaltestDataSource

reason:duplicate other project's jndi name

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2
- [x] 1.0.4

**Comment by kazuki43zoo** [comment]
@btishiwatasns 

Please modify below files.

* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/1.0.x/terasoluna-gfw-functionaltest-env/configs/resin-oracle/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml
* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/1.0.x/terasoluna-gfw-functionaltest-env/configs/resin-oracle/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml.env.ftl
* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/1.0.x/terasoluna-gfw-functionaltest-env/configs/resin-postgresql/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml
* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/1.0.x/terasoluna-gfw-functionaltest-env/configs/resin-postgresql/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml.env.ftl
