### ISSUE TITLE
Reflect: Apply Spring Boot 3.4.0-M2

### ISSUE THREAD

**Issue by btkawaharahd** [terasolunaorg/terasoluna-gfw-functionaltest#1118]
## Original Issue
> Links to the original issues.

- Reflect terasolunaorg/terasoluna-gfw#1338

## Description
> Please write if the description of the original issue is not enough.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

LobHandler/DefaultLobHandler in package org.springframework.jdbc.support.lob is now deprecated.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Please write if the description of the original issue is not enough.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Fix to not use deprecated LobHandler/DefaultLobHandler

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
Deprecated since Spring Framework 6.2.0-M1, Spring Boot 3.4.0-M1 to be exact.
