### ISSUE TITLE
Add new configuration for Tomcat8+PostgreSQL

### ISSUE THREAD

**Issue by btkodakak** [terasolunaorg/terasoluna-gfw-functionaltest#198]
## Description
Add new configuration / profile for Tomcat 8 environment with ProstgreSQL.

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
- [x] 5.1.0.RELEASE
- [x] 5.0.1.RELEASE
- [x] 1.0.3.RELEASE

**Comment by btshimizukza** [comment]
@btobaramr 

Please backport to 1.0.x.
Tomcat8+PostgreSQL is needs to test on 1.0.3.RELEASE.
