### ISSUE TITLE
Add new configuration for Tomcat8+Oracle

### ISSUE THREAD

**Issue by btkodakak** [terasolunaorg/terasoluna-gfw-functionaltest#199]
## Description
Add new configuration / profile for Tomcat 8 environment with Oracle Database.

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
- [x] 5.0.1.RELEASE
- [x] 5.1.0.RELEASE

**Comment by btshimizukza** [comment]
Does not exist the maven profile for `tomcat8-oracle` in `terasoluna-gfw-functionaltest-env` project.

**Comment by btshimizukza** [comment]
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/199#issuecomment-120264855 has been resolved.
