### ISSUE TITLE
xml-apis jar issue during spring 4.2.0.RC1 Backward compatability test execution.

### ISSUE THREAD

**Issue by btundes** [terasolunaorg/terasoluna-gfw-functionaltest#218]
## Description
The Spring IO 1.1.1/1.1.2.RELEASE uses xml-apis version 1.4.01 where as 
the Spring IO 2.0.0-BUILD.SNAPSHOT uses xml-apis of version 1.3.04.
As a result of this, while executing the selenium automated tests using the latest spring io, NoclassFound error is thown at runtime.(ElementTravesal.java class is not found).
The test execution of spring-functionaltest cannot proceed further.

## Possible Solutions
Override xml-apis Dependency in pom of terasoluna-gfw-functionaltest-parent under <dependencyManagement> as below -

```xml
.....
<dependency>
     <groupId>xml-apis</groupId>
     <artifactId>xml-apis</artifactId>
     <version>1.4.01</version>
     <scope>runtime</scope>
</dependency>
.....
```
## Issue Links
spring-functionaltest/issues/ #214

**Comment by btshimizukza** [comment]
If the spring-io-platform resolved the https://github.com/spring-io/platform/issues/220 and published a snapshot version to the maven repository, probably this issue will be resolved.
In other words, we can remove a workaround.

**Comment by btshimizukza** [comment]
this issue resolved via https://github.com/spring-io/platform/commit/3102373d8d84f331d049f7def7a3fa4ce8b6bf5e
