### ISSUE TITLE
Spring security changes in 4.0.1.RELEASE impacts the security related implementations.

### ISSUE THREAD

**Issue by btundes** [terasolunaorg/terasoluna-gfw-functionaltest#220]
## Description
All the test cases having login form with defualt field names as j_username and j_password for username and password fields respectively are failing.
Following test cases are failing-
1	RedirectTest
 	   test01_02_hiddenRedirectToNotDefined()
	   test01_01_redirectToValidInternalLink()
	   test01_05_redirectToValidInternalLink()

 2	 LoggingTest
          test02_06_createCustomUserIdMDCBeforeLogin()
	  test02_02_createCustomUserIdMDCBeforeLogin()
	  test02_01_createDefaultUserIdMDCBeforeLogin()
	  test02_04_createCustomUserIdMDCBeforeLogin()

## Possible Solutions
The spring io platform uses the 4.0.1.RELEASE vsersion of spring-security-web.
All the default names as mentioned in the below mentioned explanation link needs to be changed accordingly-
https://jira.spring.io/browse/SEC-2783 
e.g.
j_username -> username
j_password -> password
j_spring_security_check -> login
j_spring_cas_security_check -> login/cas
j_spring_cas_security_proxyreceptor -> login/cas/proxyreceptor
j_spring_openid_security_login -> login/openid
j_spring_security_switch_user -> login/impersonate
j_spring_security_exit_user -> logout/impersonate
login_error -> error
use-expressions=true by default

## Affects Version/s
N/A

## Fix Version/s
N/A

## Issue Links
* #271

**Comment by btshimizukza** [comment]
I've fixed via #271.
This issue is closed.
