### ISSUE TITLE
Adding f:query test case when the target object contains nested field

### ISSUE THREAD

**Issue by btkatoutkm** [terasolunaorg/terasoluna-gfw-functionaltest#223]
see terasolunaorg/terasoluna-gfw#297 .

# Fixed Versions

- [x] 5.1.0.RELEASE
- [x] 5.0.1.RELEASE

**Comment by kazuki43zoo** [comment]
Hi @btkatoutkm , i resolved failures in existing test cases for f:query() via #235 .
If it was merged into master branch, please it apply to your work branch(e.g. `git rebase`).

And ...
Please check validity/integrity of specification changes of f:query **in existing test cases**.
If found a problem, please modify test code or test case document or both.

**Comment by btshimizukza** [comment]
@btkatoutkm 

Please check & join discussions of #232 .
