### ISSUE TITLE
ojdbc version update

### ISSUE THREAD

**Issue by ishiharatmy** [terasolunaorg/terasoluna-gfw-functionaltest#250]
## Description
version of ojdbc driver has not been updated.

## Possible Solutions
Download the latest ojdbc driver and commit it to "terasoluna-gfw-functionaltest-env".
Update the version of ojdbc driver in pom.xml.

## Fix Version/s
- [x] 5.0.2
- [x] 5.1.0 

## Issue Links

**Comment by kazuki43zoo** [comment]
@akimotokn 

[pom.xml of init-db project](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-initdb/pom.xml#L44-L45) should be change.
