### ISSUE TITLE
Create README.md & CONTRIBUTING.md

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-gfw-functionaltest#266]
## Description
\-

## Possible Solutions
Create `README.md` & `CONTRIBUTING.md`.

* Overview description
* How to run
* How to contribute
* etc ...

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2
- [x] 1.0.4

## Issue Links
N/A

**Comment by kazuki43zoo** [comment]
@ikeyat 

Need backporting to 1.0.x ?

**Comment by ikeyat** [comment]
@kazuki43zoo 
Yes. Please backport to 1.0.x because other repos have those files.
