### ISSUE TITLE
Use JSTL impl provided by Java EE servers except Tomcat

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw-functionaltest#301]
## Description
~~Some common libraries in TERASOLUNA framework such as custom taglibs are strongly dependent on JSTL API and Implementation.
Our testing policy for them was decided to test them with Apache Taglibs included in TERASOLUNA framework stack.~~

~~Some configurations for Java EE products (WebLogic, JBoss EAP) are missing for it.
We need to fix them to be applied.
Configurations for Tomcat are OK because tomcat does not provide JSTL implementation by default.~~

* In https://github.com/terasolunaorg/terasoluna-gfw/issues/524, dependency to taglibs-standard-jstlel changed provided scope and optional, because each J2ee servers should use tag libraries itself has.
* For Tomcat, it is necessary to add a dependency to taglibs-standard-jstlel in web application.

## Possible Solutions
* WebLogic
    * ~~include ``<dependency>``~~
* JBoss EAP
    * ~~add JSTL in ``<exclusions>`` or ``<exclude-subsystems>``  of deployment.xml~~

* In terasoluna-gfw-functionaltest-env project, add a dependency to taglibs-standard-jstlel when build with `tomcat*` or default profile. If build other profiles (environments), use J2ee server's tag libraries.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE

## Issue Links
https://docs.oracle.com/cd/E50629_01/wls/WLPRG/classloading.htm#i1097628
https://access.redhat.com/documentation/ja-JP/JBoss_Enterprise_Application_Platform/6.4/html/Development_Guide/chap-Class_Loading_and_Modules.html#Class_Loading_Precedence
https://github.com/terasolunaorg/terasoluna-gfw/issues/329
https://github.com/terasolunaorg/terasoluna-gfw/issues/524

**Comment by ikeyat** [comment]
**Pending** because it is false that common libraries depend on JSTL.
In such a case, it is better to test with provided JSTL implementation by Java EE servers except Tomcat.

**Comment by ikeyat** [comment]
We do this with using replace-config template.

**Comment by ikeyat** [comment]
After internal discussion we prefer to use JSTL implementation by JavaEE if possible.
Only when application server does not provide JSTL implementation eg. tomcat, Apache Taglibs's JSTL should be used.

**Comment by ikeyat** [comment]
I changed milestone because this change impacts our release preparation.

**Comment by btyoshikawaa** [comment]
I edited this issue description responding https://github.com/terasolunaorg/terasoluna-gfw/issues/524.
