### ISSUE TITLE
Replace xxx-parent module to root pom.xml

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw-functionaltest#302]
## Description
Replace xxx-parent module to root pom.xml to follow blank projects.

## Affects Version/s
* 5.0.1.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE
- [x] 5.1.1.RELEASE
- [x] 5.0.3.RELEASE
- [x] 1.0.5.RELEASE

**Comment by btishiwatasns** [comment]
commit id d13dd50 for #303.
It has already been merged in #303.
d13dd50 is no relation to this issue.

**Comment by ikeyat** [comment]
Please backport the update of readme as done #437.

**Comment by btyoshikawaa** [comment]
Correct wrong setting on `tomcat-postgresql`.
- [ ] 5.2.0
- [ ] 5.1.1
- [ ] 5.0.3
- [ ] 1.0.5
