### ISSUE TITLE
weblogic.xml and jboss-deployment-structure.xml directly has been put on WEB-INF.

### ISSUE THREAD

**Issue by btishiwatasns** [terasolunaorg/terasoluna-gfw-functionaltest#315]
## Description
These files should be to the environment dependent.

## Affects Version/s
* 1.0.x
* 5.0.x

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.1
- [x] 5.0.3
- [x] 1.0.5

## Issue Links
N/A

**Comment by ikeyat** [comment]
Leave a comment
