### ISSUE TITLE
Local test stopped because of proxy auth

### ISSUE THREAD

**Issue by bttanakagn** [terasolunaorg/terasoluna-gfw-functionaltest#432]
## Description
Selenium test stopped by proxy authentication window when tested in local PC that required proxy authentication to connect external network.
If through a proxy authentication, the test is continued.

## Fix Version/s

- [x] 5.2.0
- [ ] 5.1.1
- [ ] 5.0.3
- [ ] 1.0.5

**Comment by iwanagah** [comment]
Please backport
