### ISSUE TITLE
JUnit Testcase Improvement

### ISSUE THREAD

**Issue by btsatoukzn** [terasolunaorg/terasoluna-gfw-functionaltest#433]
## Description
The functional test is intended to operation check on the AP server.
But, part of the functional test has been carried out in a JUnit test case.
In this case, not a valid test.

## Possible Solutions
Modified to be run on the application server.

## Affects Version/s
* 5.1.0.RELEASE

## Fix Version/s
* 5.2.0.RELEASE
  - [x] codepoint
  - [x] string
* 5.1.1.RELEASE
  - [x] codepoint
  - [x] string

## Issue Links
*

**Comment by btyoshikawaa** [comment]
@btsatoukzn 
Please backport to 5.1.x from #452 .
