### ISSUE TITLE
SQLFeatureNotSupportedException is output in the Postgresql JDBC at startup

### ISSUE THREAD

**Issue by btkadotahr** [terasolunaorg/terasoluna-gfw-functionaltest#441]
## Description
In the Postgresql JDBC at start-up, the following error log is output (start-up is successful).
```
date:2016-05-31 16:33:40	thread:localhost-startStop-1	X-Track:	level:ERROR	logger:jdbc.audit                                      	message:1. Connection.createClob()
java.sql.SQLFeatureNotSupportedException: org.postgresql.jdbc4.Jdbc4Connection.createClob() メソッドはまだ実装されていません。
```

## Possible Solutions
Add property file `hibernate.properties` in terasoluna-tourreservation-web resource folder, and add the following setting.

```properties
hibernate.jdbc.lob.non_contextual_creation = true
```

ref https://forum.hibernate.org/viewtopic.php?f=1&t=1033685&view=previous

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.0

## Issue Links
* https://github.com/terasolunaorg/terasoluna-tourreservation/issues/380

**Comment by btyoshikawaa** [comment]
@btkatoutmj 
Please backport.
