### ISSUE TITLE
Apply maven-formatter-plugin

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/terasoluna-gfw-functionaltest#448]
## Description
We are going to removed `maven-formatter-plugin` from plugin management of `terasoluna-gfw-parent`.
So We should add that plugin into this project for code formatting.
( Such as the maven-license-plugin, corresponding If there is to be a similar treatment to the other )

## Possible Solutions
* add configuration of `maven-formatter-plugin` into `terasoluna-gfw-functionaltest/pom.xml`
* add `terasoluna-gfw-functionaltest/eclipse/formatter.xml` from `terasoluna-gfw/(same-path)`.

## Affects Version/s
* 5.2.0.RELEASE

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.1
- [x] 5.0.3
- [x] 1.0.5

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/538

**Comment by sasakitsy** [comment]
This problem will be fixed at #428

**Comment by ikeyat** [comment]
#428  has been done. Close this issue.

**Comment by btyoshikawaa** [comment]
@ikeyat @sasakitsy 
This problem fixed at #428 version 5.2.0 only. We should be able to format even version 5.1.1 and earlier.
It can be resolved by adding a `terasoluna-gfw-functionaltest/eclipse/formatter.xml` to those versions.

**Comment by btyoshikawaa** [comment]
@btkukinom 
Please backport to earlier versions.

**Comment by btyoshikawaa** [comment]
@iwanagah 
I'd merged all versions. So this issue will be included in the 5.2.0.RC2 .
