### ISSUE TITLE
Domain project depends on postgresql and ojdbc7 with runtime scope

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/terasoluna-gfw-functionaltest#451]
## Description
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-domain/pom.xml#L54
When gfw-func connect to Postgresql or Oracle database, it is used JNDI Resouse.
But gfw-func domain project depends on `postgresql` and `ojdbc7` with `runtime` scope unnecessarily.

And `db2jcc4` is not exist in domain project dependencies. this is unnecessarily to run application, but It should be treated the same as other jdbc libraries.

## Possible Solutions
* Change scope of `postgresql` and `ojdbc7` dependencies to `provided`. (`ojdbc7` and `db2jcc4` as well)
* Add dependency on `postgresql` in configuration of `cargo-maven2-plugin` for Travis-CI.

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE
* 1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.1
- [x] 5.0.3
- [x] 1.0.5

## Issue Links
* #XXX

**Comment by iwanagah** [comment]
Please backport
