### ISSUE TITLE
Add special flow of TransactionToken

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw-functionaltest#463]
## Description
TBD

## Possible Solutions
TBD

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.0-5.0.2.RELEASE
* 1.0.0-1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE
- [x] 5.1.1.RELEASE

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/565

**Comment by btyoshikawaa** [comment]
@btkobayashirun 
Please backport #485 to 5.1.x .
