### ISSUE TITLE
Functional test could fail due to unsupported Firefox version

### ISSUE THREAD

**Issue by xzjia** [terasolunaorg/terasoluna-gfw-functionaltest#504]
## Description
Since selenium relies on Firefox to run functional tests, those tests could fail due to unsupported Firefox versions. 
But this is not mentioned in README.rd.

## Possible Solutions
Add link to selenium changelog, providing hints for why tests failed.
Or, explicitly specify Firefox versions. (perhaps not a good idea)

## Fix Versions
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6 * Commited directly to the maintenance branch.

**Comment by ikeyat** [comment]
We've mentioned to the supported version of FireFox as follows.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/wiki/Tested-Environment

Anyway it's better to be written in ``README.md`` as you reported.

**Comment by btyoshikawaa** [comment]
@xzjia 
Please backport each version branches!

**Comment by xzjia** [comment]
@btyoshikawaa Back port pull request sent for version 5.0.x, 5.1.x, 5.2.x (#518, #519, #520).
Already merged into branch 1.0.x (accidentally).

**Comment by btyoshikawaa** [comment]
@xzjia 
Oh... Please be careful.
