### ISSUE TITLE
Create new profile for Tomcat 8.5 + PostgreSQL 9

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-functionaltest#506]
## Description
We'll support Tomcat 8.5 + PostgreSQL 9 as new test environment.

## Possible Solutions
Add `tomcat85-postgresql` profile.

## Affects Version/s
\-

## Fix Version/s
- [x] 5.3.0
- [x] rework for 5.3.0
- [x] 5.2.1

## Issue Links
N/A

**Comment by kazuki43zoo** [comment]
@bttamuratsh 

Please support this.

**Comment by kazuki43zoo** [comment]
@bttamuratsh 

Please fix https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/510#pullrequestreview-10061695 .

**Comment by bttamuratsh** [comment]
@kazuki43zoo I fixed the indent.

**Comment by kazuki43zoo** [comment]
@bttamuratsh please submit PR for fixing an indent !

**Comment by kazuki43zoo** [comment]
We need to backport to 5.2.x branch.
