### ISSUE TITLE
Support Spring IO Platform Athens-SR2

### ISSUE THREAD

**Issue by bturamatuyu** [terasolunaorg/terasoluna-gfw-functionaltest#517]
## Description
I try to run gfw-functionaltest with terasoluna-gfw build with Spring IO Athens-SR1

Tested branch is below：
issues/563_Spring_IO_PF_Athens_For_1.4.1.BUILD-SNAPSHOT

but,I found following errors：
- Failed ElTest#test06_Query_Display on Support Spring IO Platform Athens-SR1(#516)
- Failed RedirectTest#test01_05_redirectToValidInternalLink on Support Spring IO Platform Athens-SR1 (#515)
- Failed ElTest#test06_16_ListOfSimpleValueDefaultTrim on Support Spring IO Platform Athens-SR1(#514)
- Failed ExceptionHandlingTest#test04_02_webApplicationHandling in Support Spring IO Platform Athens-SR1(#513)

travis-ci result is below:
https://travis-ci.org/terasolunaorg/terasoluna-gfw-functionaltest/builds/179663388

## Possible Solutions
undecided

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.3.0.RELEASE
- [x] 5.3.0.RELEASE update for test case design
- [x] 5.3.0.RELESAE update tests to apply modification of test case design
- [x] 5.3.0.RELESAE reflect changes https://github.com/terasolunaorg/guideline/issues/2368

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/563

**Comment by kazuki43zoo** [comment]
@bthondasui 

Please update test case design on [wiki page](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/wiki).

**Comment by kazuki43zoo** [comment]
@bthondasui 

Plesae update tests to apply modification of test case design.

**Comment by bthondasui** [comment]
The Consideration content of the guideline was reflected in the test code.
[guideline/issues/2368](https://github.com/terasolunaorg/guideline/issues/2368)

**Comment by bthondasui** [comment]
ガイドラインに設定方法を合わせる。（動きに影響はない）
spring-mvc.xmlのSystemExceptionResolverにNestedServletExceptionを除外する設定について、setで複数指定できるようにし、記載場所を変更した。それに合わせてterasoluna-gfw-functionaltestのspring-mvc.xmlも修正する。
[guidline#2368](https://github.com/terasolunaorg/guideline/issues/2368)
