### ISSUE TITLE
Apply build java-version 1.8

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/terasoluna-gfw-functionaltest#528]
## Description
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/f13f5c6b30dca445c92a3735d7c3f1f3e968fc11/pom.xml#L276
To align test conditions, make it possible to change `java-version` 1.7 and 1.8 .
This issue is maintenance task for release 2017 winter and later.

## Possible Solutions
* Change default of `java-version` property to 1.8 .
* ~~Make it possible to change `java-version` property by using maven profile activate with build jdk version.~~

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6

#### Reflect to README.md
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6

## Issue Links
* #XXX

**Comment by btyoshikawaa** [comment]
In 5.0.x and 1.0.x ,wrong commit message.
Java version is changed not from 1.7 to 1.8, but from 1.6 to 1.8 .

**Comment by btyanagawamg** [comment]
for Fix README.md, re-open this issue.
