### ISSUE TITLE
Support JBoss EAP 6 on 5.3.0

### ISSUE THREAD

**Issue by bttamuratsh** [terasolunaorg/terasoluna-gfw-functionaltest#545]
## Description
In 5.3.0.RC1, the test has failed because of conflicting jboss-logging library in war file with the one in the modlue of JBoss6.

## Possible Solutions
exclude jboss-logging module from a deployment

## Affects Version/s
* 5.3.0

## Fix Version/s
Apply workaround

- [x] 5.3.0.RELEASE #546 

Apply full-blown countermeasures

- [x] 5.3.0.RELEASE

## Issue Links
* #584

**Comment by kazuki43zoo** [comment]
I've applied as workaround for pre-test. But I think we should consider full-blown countermeasures.

**Comment by kazuki43zoo** [comment]
@bttamuratsh 

> optimize jboss6 module structure

Please create a issue for backport.
