### ISSUE TITLE
Update README.md (2017 winter)

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/terasoluna-gfw-functionaltest#610]
# Description
fix travis-ci badge in README.md on 5.3.x  (branch=master -> branch=5.3.x)
modify "How to contribute" URL, from absolute path to relative path on master branch and 5.3.x branch

## Fix Version/s
- [x] master
- [x] 5.3.x

#### reflect [contributing guideline]
- [x] 5.2.x
- [x] 5.1.x
- [x] 5.0.x
- [x] 1.0.x

**Comment by yoshikawaa** [comment]
@bturamatuyu 
Please reflect to change link URL of [contributing guideline] to 5.2.x and earlier.
