### ISSUE TITLE
Consider to use the HtmlUnitDriver for speed up

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-functionaltest#626]
## Description
Currently, total time of all tests take about 6 minutes. I think it can be improved more.

## Possible Solutions

I propose to use the `HtmlUnitDriver` instead of `FirefoxDriver`.

Before(`FirefoxDriver`): About 6 minutes
After(`HtmlUnitDriver`): About 2 minutes

* Build result see [here](https://travis-ci.org/kazuki43zoo/terasoluna-gfw-functionaltest/builds/222549490#L8459).
* Changes see [here](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/compare/master...kazuki43zoo:htmlunit).  

**Note:**
I've tried parallel execution( using forkCount=2 ).
Total time was 01:23 min.

* https://travis-ci.org/kazuki43zoo/terasoluna-gfw-functionaltest/builds/222569395
* https://s3.amazonaws.com/archive.travis-ci.org/jobs/222569396/log.txt

## Affects Version/s
* All versions

## Fix Version/s
(To be written later by project member)

## Issue Links
N/A

**Comment by yoshikawaa** [comment]
Already done. consider again the main browser with #858.
