### ISSUE TITLE
Resolve "TODO" in test cases

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-functionaltest#627]
## Description
`TODO` remains in some test cases.

* For Example: [ExceptionHandlingTest#test02_02_useCaseControllerHandling](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java#L94)
  - In Wiki test requirement
    ```
    HandlerExceptionResolverLoggingInterceptorのログが出力されることの確認のテスト
    ステータスコードが200の場合、INFOログが出力されることのテスト
    ````
  - In test case (source code)
    `TODO Assert Output Log`
    Now, assert only string output on screen...

We must check that these meet the test requirements, and correct them if necessary.

#### Target test case
* [ExceptionHandlingTest](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java)
  ※ All test case except　`test02_01_useCaseControllerHandling`.

* TransactionTokenTest
  - [test03_02_customTokenStoreSizeOverClassMethodNamespace](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java#L590)

## Possible Solutions
Fix to assert log.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1
- [x] 5.2.2
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.7

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/702

**Comment by kazuki43zoo** [comment]
good catch !

**Comment by yoshikawaa** [comment]
Pending https://github.com/terasolunaorg/terasoluna-gfw/issues/702

**Comment by yoshikawaa** [comment]
@bttanakaysd Thanks for your work.
