### ISSUE TITLE
In travis , MessageTest failure happened

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-gfw-functionaltest#637]
## Description
[In travis , error happen at tagConfiguration_10_01 test](https://travis-ci.org/terasolunaorg/terasoluna-gfw-functionaltest/builds/244401409?utm_source=email&utm_medium=notification) .
The flow of the test is as follows .
- controller([MessageController.java#test10_01_tagConfiguration](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/message/MessageController.java#L384)) stores the message([`i.gt.me.0007`](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-web/src/main/resources/i18n/application-messages_en.properties#L8)) in the model .
- jsp([tagConfiguration.jsp](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/message/tagConfiguration.jsp#L4))displays message([`i.gt.me.0007`](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-web/src/main/resources/i18n/application-messages_en.properties#L8)) .
- selenium([MessageTest.java#test10_01_tagConfiguration](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/message/MessageTest.java#L717)) check whether message displayed .

  In Wiki test requirement is as follows .
    ```
    出力対象が存在しない場合に、innerElementに開始・終了タグが出力されることを確認するテスト
    "<div class="alert alert-success"><ul><li></li></ul></div>"が出力されていること
    ````

#### reason
As long as I checked the source code , the confirmation item should be displayed normally on the screen .

#### analyze
My idea of a test failure is that before the result confirmation screen was displayed, screen was asserted and test failed .

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
It has not occurred for a long time.
