### ISSUE TITLE
extend waitForAssertion time

### ISSUE THREAD

**Issue by itouyun** [terasolunaorg/terasoluna-gfw-functionaltest#675]
## Description
Travis happens rare error because of IO timing. (For example https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/674#issuecomment-324806205 )

- waiting time is too shote
  - https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java#L50
  - https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java#L71

- default waiting time is 50 ms.
  - https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/DBLogProvider.java#L38

## Possible Solutions
The solution is a multiple.
- Fundamental Resolution
  - asserting a screen title before the log assertion ( https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/675#issuecomment-326515590 )
- Expand Sleeping Time
  - change to `public void waitForAssertion(long waitTime)` from `public void waitForAssertion()` on ExceptionHandlingTest.java
  - elongate default waiting time to `xxx ms` from 50ms in `public void waitForAssertion()`
  - user can set default waiting time by `selenium.properties`
    - Thread.sleep( 50ms + `user setting time`  )

We consider solution.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)

## Final Solution
- Fundamental Resolution
  - asserting a screen title before the log assertion ( https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/675#issuecomment-326515590 )

## Issue Links
* #XXX

**Comment by itouyun** [comment]
We will fix all version because we must fix timing problems.

**Comment by kazuki43zoo** [comment]
@itouyun

Probably, I think this issue can resolve by asserting a screen title before the log assertion.
I suggest to reconsider a possible solution.

**Comment by itouyun** [comment]
@kazuki43zoo 
Should we add code `assertTrue(driver.getTitle().contains("Title of Page"));` (<- example) before the log assertion on `test01_01_requestControllerHandling()` and `test01_02_requestControllerHandling()` ?

**Comment by kazuki43zoo** [comment]
yes.

**Comment by itouyun** [comment]
@kazuki43zoo 
Thank you!
I update Possible Solutions. We will check validity of `Fundamental Resolution`.

**Comment by itouyun** [comment]
We will do `Fundamental Resolution`.

**Comment by yoshikawaa** [comment]
@kazuki43zoo @itouyun 
I think more better to use `WebDriverWait`, but we can't use this because depend on Java 8 and later...
