### ISSUE TITLE
Remove definition of trimTokens

### ISSUE THREAD

**Issue by bttsuchikawaf** [terasolunaorg/terasoluna-gfw-functionaltest#682]
## Description
Definition of  `trimTokens=false`  is default,  `trimTokens=false`  is not necessary.

## Possible Solutions
 `pathMatcher` default is  `org.springframework.util.AntPathMatcher`.
AntPathMatcher has field "trimTokens" that defalt is false.
 for that reason, Remove it

https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
```
 <mvc:path-matching path-matcher="pathMatcher" /> 

 <bean id="pathMatcher" class="org.springframework.util.AntPathMatcher"> 
     <property name="trimTokens" value="false" /> 
 </bean> 
```

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1 (5.3.x)

## Final Solution
do PossibleSolution

## Issue Links
* terasolunaorg/terasoluna-gfw-web-multi-blank#334 (terasoluna-gfw-web-multi-blank)
* terasolunaorg/guideline#2941 (guideline)

**Comment by itouyun** [comment]
@btoohashimc 
Thank you for your work!!!
