### ISSUE TITLE
Travis CI Broken using Selenium.

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-functionaltest#706]
## Description
Cause `BeanCreationException`, because `UnsupportedCommandException` (Bad Request) occurred at `WebDriver` creation.

https://travis-ci.org/terasolunaorg/terasoluna-gfw-functionaltest/builds/307773573?utm_source=github_status&utm_medium=notification

```console
test08_02_form(org.terasoluna.gfw.functionaltest.app.codelist.CodeListTest)  Time elapsed: 1.597 sec  <<< ERROR!
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webDriver': FactoryBean threw exception on object creation; nested exception is org.openqa.selenium.UnsupportedCommandException: Bad request
Command duration or timeout: 151 milliseconds
```

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0 (master)
- [x] 5.4.1 (5.4.x)
- [x] 5.3.2 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
May be related SeleniumHQ/selenium#431

**Comment by btkatagiriyu** [comment]
It seems that this issue is related.
https://github.com/travis-ci/travis-ci/issues/8780

**Comment by hosoitk** [comment]
I saw #713 .
Why does /etc/hosts change to write [before_install: sudo sh -c 'echo "127.0.0.1" >> /etc/hosts']?
(You use additional redirect.)

before /etc/hosts:
127.0.0.1	localhost
::1	 ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.55	travis-job-terasolunaorg-guideline-327138929.travisci.net travis-job-terasolunaorg-guideline-327138929

after /etc/hosts:
127.0.0.1 localhost nettuno travis vagrant
127.0.1.1 travis-job-2880d964-5ac2-4c44-bf3e-93b19851b8fd travis-job-2880d964-5ac2-4c44-bf3e-93b19851b8fd ip4-loopback trusty64

**Comment by btkatagiriyu** [comment]
Setting ```sudo required``` seems to enable 127.0.0.1 address.
There is no need to change ```/etc /hosts```.

**Comment by yoshikawaa** [comment]
@btkatagiriyu @hosoitk 
It changed from a container to a VM, but fortunately it seemed that performance was good, so I was relieved.

@hosoitk 
Please correct "Fix Version/s", and manage backport.
