### ISSUE TITLE
update copyright (2017 -> 2018)

### ISSUE THREAD

**Issue by btkatoutmj** [terasolunaorg/terasoluna-gfw-functionaltest#717]
## Description
update copyright (2017 -> 2018)

## Possible Solutions
update license/header.txt
and use `mvn lisence:format`

## Affects Version/s
* 5.4.1.RELEASE
* 5.3.2.RELEASE

## Fix Version/s
- [ ] master
- [ ] 5.4.x
- [ ] 5.3.x

## Final Solution
(To be written later by project member)

## Issue Links
none

**Comment by btkobayashirun** [comment]
#809
