### ISSUE TITLE
create profile for tomcat9-postgresql

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw-functionaltest#726]
## Description
create profile to use tomcat 9.0.6 and PostgreSQL 10.2

## Possible Solutions
TBD

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0(master)
~~[ ] 5.4.2 (5.4.x)~~ (not support tomcat9)

## Final Solution
TBD

## Issue Links
* #XXX

**Comment by hirakuriy** [comment]
I'll close this issue, because backporting to 5.4.x is not necessary.
