### ISSUE TITLE
[Selenium 3.0] Update from Selenium 2 to Selenium 3

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw-functionaltest#740]
## Description
selenium update.

## Additional functions
- Update Selenium version to `3.0.1`
- Add webdrivermanager version `1.6.2`
- Update travisCI Firefox version to `52.9.0esr`
- Added property of geckodriver and webdrivermanager
- Implement setup on `FirefoxDriverFactoryBean.java` to use geckodriver
- Add test method to Readme

## Possible Solutions
Resolving errors with selenium update.
- Implement `WaitWebDriverEventListener.java` due to bug of geckodriver  
- To avoid Firefox crash, put `driver.get("about:config")` before `driver.quit()`  
- Create `WebDriverOperations#getTextMatchLink` for getting webElement containing blank literal
- Fix `ElTest#test05_URL_Link` for link access impossible at Jenkins

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.1
- [x] 5.4.2 (Apply changes without selenium 3 unique.)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
Finary update as follows.
* Selenium 3.14.0
* WebDriverManager 3.1.1
* GeckoDriver v0.23.0
* Firefox 60.3 ESR

**Comment by yoshikawaa** [comment]
@hirakuriy @btiwahorisu 
It seems better to do backport the part that works with Selenium 2 and 3 in the same implementation.
