### ISSUE TITLE
create profile for tomcat9-oracle

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-gfw-functionaltest#746]
## Description
create profile to use tomcat 9.0.6 and Oracle12c

## Possible Solutions
TBD

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0(master)
~~[ ] 5.4.2 (5.4.x)~~ (tomcat9での検証は行わない)

## Final Solution
TBD

## Issue Links
* #XXX

**Comment by hirakuriy** [comment]
バックポートは不要であるためclose
