### ISSUE TITLE
Fixed source code pointed out by SonarQube

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw-functionaltest#754]
## Description
Fix Critical and Blocker of Severity due to Bug / Vulnerability / Code Smell problem pointed out on SonarQube.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [ ] master(5.5.0)
- [ ] 5.4.x

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
This is done in development with each release.
