### ISSUE TITLE
Travis CI broken with failing to install oraclejdk8

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-functionaltest#814]
## Description
Travis CI broken with failing to install oraclejdk8.
https://travis-ci.org/terasolunaorg/terasoluna-gfw-functionaltest/jobs/556803469#L167

Discussion of Travis CI Community.
https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766

Docs of Travis CI. (not reflected...)
Precise : https://docs.travis-ci.com/user/reference/precise/#jvm-clojure-groovy-java-scala-vm-images
Trusty : https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images

Failing point is ...
current : https://github.com/sormuras/bach/blob/master/install-jdk.sh#L183-L185
changes : https://github.com/sormuras/bach/commit/d35b7ddaa5ef9b05141cbfdd45733ff126856b38#diff-08dca971d5e4fbd0624e7bf955f5adb1

## Possible Solutions
* Consider updating to JDK 9 or higher.
* [Workaround?] change to `openjdk8`.

## Final Solution

- We use only open jdk(8 and 11) in travis ci at our all repository .
- In addition, for branches prior to 5.4.x at our all repository, we decide to use Trusty environment (at Trusty environment, we use the same JDK as before) in travis ci .

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.6.0 (master)
- [x] 5.5.2 (5.5.x)
- [x] 5.4.3 (5.4.x)
- [x] 5.3.3 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)

## Issue Links
- #XXX

**Comment by btyanagawamg** [comment]
We use default "[xenial](https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support) environment", but it was changed not to install oracle jdk 8.
I propose to change to "[trusty](https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images) environment" that use oracle jdk 8 by default .

https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/commit/11e699b587152978f26cfa0e950663d3451b6912

**Comment by btyanagawamg** [comment]
Finally, we decide to use only open jdk(8 and 11) in travis ci at our all repository .

**Comment by btyanagawamg** [comment]
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/814#issuecomment-542064790

In addition, for branches prior to 5.4.x at our all repository, we decide to use Trusty environment (at Trusty environment, we use the same JDK as before) in travis ci .
