### ISSUE TITLE
Enable to set default class attribute to page item (inner element).

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-functionaltest#826]
## Description
Apply terasolunaorg/terasoluna-gfw#928 .

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.6.0.RELEASE

## Issue Links
- #XXX

**Comment by btiwahorisu** [comment]
close because fix ver5.6.0.
