### ISSUE TITLE
Consider E2E test browser on Travis CI

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw-functionaltest#869]
## Description
I uses firefox for test, but it is not always necessary to use firefox.Therefore, consider the best browser.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/8216fd99ebac06b03a43009690f328071326834c/.travis.yml#L8

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
duplicate #863
