### ISSUE TITLE
change terasoluna-gfw branch in travis.yml

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw-functionaltest#886]
## Description
Build with terasoluna-gfw:master in travis.yml on the 5.6.x branch.
This is an omission in #865 and you should refer to terasoluna-gfw: 5.6.x correctly.

https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/0d29f18141afc701423dc57274fb1aad16a78a1f/.travis.yml#L18

## Possible Solution
fix as follows
``` yml
 - if [[ -z $GFW_BRANCH ]]; then GFW_BRANCH=5.6.x; fi 
```

## Affect versions
- 5.6.1.RELEASE

## Issue links
- https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/865

**Comment by btkobayashirun** [comment]
Duplicate of #865
