### ISSUE TITLE
Reflect:Update the version of maven-plugin

### ISSUE THREAD

**Issue by btootomoyuk** [terasolunaorg/terasoluna-gfw-functionaltest#892]
## Original Issue
> Links to the original issues.

- Reflect https://github.com/terasolunaorg/terasoluna-gfw/issues/1083

## Description
> Please write if the description of the original issue is not enough.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Take the following actions:
- Upgrade the plugin version
- Remove unnecessary plugins.
- Change `com.google.code:maven-license-plugin` to `com.mycila:license-maven-plugin` as described in https://github.com/terasolunaorg/terasoluna-gfw/issues/600.
- Modify the variable name of the plugin version to be `groupId.artifactId.pugin.version`.
- Modify `sql-maven-plugin versioning` location to match mutli-blank settings.
https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/master/projectName-initdb/pom.xml#L55

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Update your plugins to the latest version.

**Comment by btonokit** [comment]
Reopen the plugin to match the multi-blank configuration.
See https://github.com/terasolunaorg/terasoluna-tourreservation/issues/686#issuecomment-891654903
