### ISSUE TITLE
Delete unnecessary files in the env project

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-gfw-functionaltest#957]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

There is an unused environment file in the env project.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Delete them.

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.7.0.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
Since the version of Tomcat described in the README is old, it has been corrected by this ISSUE.
`tomcat8` -> `tomcat9`
