### ISSUE TITLE
Reflect: Add logback-classic-db

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-gfw-functionaltest#982]
## Original Issue
> Links to the original issues.

- Reflect https://github.com/terasolunaorg/terasoluna-gfw/issues/1166

## Description
> Please write if the description of the original issue is not enough.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Now terasoluna-gfw does not add logback-classic-db.
Since terasoluna-gfw-functionaltest uses `ch.qos.logback.classic.db.DBAppender`, it is necessary to add logback-classic-db.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
see https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/984#pullrequestreview-1072288500
